version: "3.9"
services:
  rabbitmq:
    hostname: 'rabbit'
    image: rabbitmq:management
    container_name: 'rabbit'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - evaluation
  db:
    image: mongo
    container_name: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: students
    networks:
      - evaluation
    restart: always
networks:
  evaluation:
    driver: bridge