# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: evaluation-event ci pipeline dockerhub

on:
  workflow_dispatch:
    inputs:
      enableDockerPush:
        description: 'enable Docker Push action'
        required: false
        default: true
        type: boolean
      tag:
        description: 'docker image tag'
        required: false
        default: latest
        type: string
#  push:
#    paths:
#      - 'evaluation-api/**'
#    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: evaluation-event
      TAG: ${{ inputs.tag }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: zulu
        cache: 'gradle'
    
    - name: Gradle build
      run: |
        cd ${{ env.PROJECT }}/
        ./gradlew build
        
    - id: login-dockerhub
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ env.PROJECT }}
        push: ${{ inputs.enableDockerPush }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT }}:${{ env.TAG }}
